### ISSUE TITLE
用python2.7 32位编译train.py出现EOFError怎么解决

### ISSUE THREAD

**Issue by huyp182** [foursking1/jd#3]
求解决..

**Comment by ZS167275** [comment]
你是不是用了 pkl了？ 删除那个pkl 就可以了

**Comment by huyp182** [comment]
用了numpy+mkl。
不太清楚pkl指的是什么，但是应该没用这个吧。
这是cmd里的：
C:\Users\Administrator>pip uninstall packle
Cannot uninstall requirement packle, not installed

C:\Users\Administrator>pip uninstall pkl
Cannot uninstall requirement pkl, not installed

**Comment by huyp182** [comment]
你说的pkl是pickle.py啊...才发现，我试试

**Comment by ZS167275** [comment]
我是说删除它的中间结果就行 就是产生的中间结果

**Comment by huyp182** [comment]
谢谢，那个问题解决了，又出现了新问题..
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    xgboost_make_submission()
  File "train.py", line 18, in xgboost_make_submission
    user_index, training_data, label = make_train_set(train_start_date, train_end_date, test_start_date, test_end_date)
  File "D:\jd-master\gen_feat.py", line 272, in make_train_set
    user = get_basic_user_feat()
  File "D:\jd-master\gen_feat.py", line 46, in get_basic_user_feat
    user = pickle.load(open(dump_path))
TypeError: a bytes-like object is required, not 'str'

把dump_path改成dump_path.encode("utf-8")也没用，一样的错误

**Comment by ZS167275** [comment]
user = get_basic_user_feat() 你看看这个函数的问题

**Comment by aashish-medhatech** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @Pomelog, @mmiinnovations, @tomjrtsmith, @ilis137, @0xClandestine, @iayanami, @meigy7, @0xblockhash, @victornewkirk, @spideynolove, @snakewarhead, @0xbnb, @jiangplus, @AwesomeHuang, @2997ms, @magania, @fourseaLee
