### ISSUE TITLE
Python 3.6.1 64位和Python 2.7.13 64位都试过了，都有这个error

### ISSUE THREAD

**Issue by huyp182** [foursking1/jd#4]
错误信息如下
Traceback (most recent call last):
File "train.py", line 82, in 
xgboost_make_submission()
File "train.py", line 18, in xgboost_make_submission
user_index, training_data, label = make_train_set(train_start_date, train_end_date, test_start_date, test_end_date)
File "D:\jd-master\gen_feat.py", line 272, in make_train_set
user = get_basic_user_feat()
File "D:\jd-master\gen_feat.py", line 46, in get_basic_user_feat
user = pickle.load(open(dump_path))
TypeError: a bytes-like object is required, not 'str'

把dump_path改成dump_path.encode("utf-8")也没用，一样的错误= =

**Comment by douliyoutang** [comment]
您好，我和您遇到了相同的问题，不知道怎么解决。请问您已经解决了这个问题吗？

**Comment by huyp182** [comment]
还没有，不懂啊= =

**Comment by ZS167275** [comment]
就是他不是生成了缓存了吗，吧缓存文件删掉
